service: document-service-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    STAGE: ${opt:stage, 'dev'} # Agregar variable de entorno para el stage
    IS_OFFLINE: ${opt:isOffline, 'false'}

plugins:
  - serverless-offline

functions:
  lambdaDocument:
    name: document-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.documentHandler
    events:
      - http:
          path: /documents
          method: any
          cors: true
      - http:
          path: /documents/{id}
          method: get
          cors: true
      - http:
          path: /document-types
          method: get
          cors: true
